[package]
name = "hypercube_nets"
version = "0.1.0"
edition = "2024"

[dependencies]
mimalloc = "0.1.48"
rayon = "1.11.0"
rug = "1.28.0"
thread_local = "1.1.9"

[[bin]]
name = "hypercube_nets"
path = "src/main.rs"
