[package]
name = "hypercube_nets"
version = "0.1.0"
edition = "2024"

[dependencies]
mimalloc = "0.1.48"
num-bigint = "0.4.6"
num-integer = "0.1.46"
num-rational = "0.4.2"
num-traits = "0.2.19"
rayon = "1.11.0"
rug = "1.28.0"

[[bin]]
name = "hypercube_nets"
path = "src/main.rs"
